[package]
name = "star-wars-api-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "star-wars-api-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
async-graphql = "4.0"
async-graphql-actix-web = "4.0"